// DOM integration only. This is intentionally not a substitute for visual/WebGL QA.
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createRequire} from 'node:module';
const require=createRequire(new URL('../../experiments/mapa-territorial/package.json',import.meta.url));
const {JSDOM}=require('jsdom');
const base=new URL('../../experiments/mapa-territorial/public/',import.meta.url);
const waitUntil=async predicate=>{const start=Date.now();while(!predicate()){if(Date.now()-start>5000)throw new Error('DOM condition timed out');await new Promise(r=>setTimeout(r,15));}};
test('DOM: lazy layers, selection, sources, missing data, safe URL, back, error and fallback',async()=>{
  const html=await readFile(new URL('laboratorio/mapa-territorial/index.html',base),'utf8');
  const dom=new JSDOM(html,{url:'https://preview.invalid/laboratorio/mapa-territorial/?modo=explorar'});
  const win=dom.window;
  Object.assign(globalThis,{window:win,document:win.document,location:win.location,history:win.history,MutationObserver:win.MutationObserver,matchMedia:()=>({matches:false,addEventListener(){},removeEventListener(){}}),requestAnimationFrame:fn=>setTimeout(fn,0)});
  win.HTMLElement.prototype.scrollIntoView=function(){};
  const calls=[];let failEducation=true;
  globalThis.fetch=async input=>{
    const url=new URL(input);const rel=url.pathname.split('/assets/mapa-territorial/data/')[1];calls.push(rel);
    if(rel==='layers/educacion.geojson'&&failEducation)return {ok:false,status:503};
    const bytes=await readFile(new URL(`assets/mapa-territorial/data/${rel}`,base));return {ok:true,status:200,json:async()=>JSON.parse(bytes)};
  };
  await import('../../experiments/mapa-territorial/public/assets/mapa-territorial/app.mjs');
  const $=id=>win.document.getElementById(id);const change=(id,value)=>{$(id).value=value;$(id).dispatchEvent(new win.Event('change',{bubbles:true}));};
  await waitUntil(()=>win.__CEPOES_MAP_QA.status==='ready');
  assert.equal($('mt-territory').options.length,49);
  assert.match($('mt-status').textContent,/86 registros/);
  assert.ok(!calls.includes('layers/educacion.geojson')&&!calls.includes('layers/verdes.geojson'));
  assert.equal($('mt-territory-table').rows.length,48);
  $('mt-record-list').querySelector('[data-record]').click();assert.equal($('mt-service-card').hidden,false);change('mt-category','Hospital');assert.equal($('mt-service-card').hidden,true);change('mt-category','');
  change('mt-territory','barrio:agronomia');assert.equal($('mt-place-name').textContent,'Agronomía');assert.match(win.location.search,/territorio=barrio%3Aagronomia/);
  change('mt-level','comuna');assert.equal($('mt-territory').options.length,16);assert.equal($('mt-territory-table').rows.length,15);
  $('mt-record-list').querySelector('[data-record]').click();assert.equal($('mt-service-card').hidden,false);
  win.document.querySelector('[data-layer="educacion"]').click();assert.equal($('mt-service-card').hidden,true);assert.equal($('mt-territory-table').rows.length,0);await waitUntil(()=>win.__CEPOES_MAP_QA.status==='layer-error');
  assert.match($('mt-error-text').textContent,/HTTP 503/);assert.equal($('mt-record-count').textContent,'Sin dato');assert.equal($('mt-territory-table').rows.length,0);
  failEducation=false;$('mt-retry').click();await waitUntil(()=>win.__CEPOES_MAP_QA.status==='ready');
  assert.match($('mt-status').textContent,/2\.732 registros/);assert.match($('mt-status').textContent,/60 sin punto verificable/);
  change('mt-category','Estatal');assert.equal($('mt-category').value,'Estatal');
  win.history.pushState(null,'','?capa=educacion&escala=comuna');win.dispatchEvent(new win.PopStateEvent('popstate'));assert.equal($('mt-category').value,'');assert.match($('mt-status').textContent,/2\.732 registros/);
  assert.match($('mt-method').textContent,/Corte de observación/);assert.match($('mt-sources').textContent,/CC-BY-2.5-AR/);
  win.document.querySelector('[data-layer="verdes"]').click();await waitUntil(()=>$('mt-status').textContent.includes('2.176 registros'));
  assert.match($('mt-error-text').textContent,/41 registros/);assert.match($('mt-metrics').textContent,/Comparación territorial en revisión/);assert.match($('mt-status').textContent,/2\.135 puntos verificados/);
  assert.ok([...$('mt-territory-table').rows].every(r=>r.cells[2].textContent==='En revisión'));
  $('mt-record-search').value='Plaza';$('mt-record-search').dispatchEvent(new win.Event('input'));assert.ok($('mt-record-list').children.length>0);
  $('mt-share').click();assert.ok(!$('mt-share-url').hidden);assert.ok(!$('mt-share-url').value.includes('Plaza'));
  win.history.pushState(null,'','?capa=salud&escala=barrio&territorio=barrio:la-boca');win.dispatchEvent(new win.PopStateEvent('popstate'));await waitUntil(()=>$('mt-place-name').textContent==='La Boca'&&$('mt-status').textContent.includes('registros en La Boca'));
  assert.equal(calls.filter(x=>x==='layers/salud.geojson').length,1,'loaded layer reused from cache');
  $('mt-reset').click();assert.equal($('mt-place-name').textContent,'Toda la Ciudad');
  await waitUntil(()=>win.__CEPOES_MAP_QA.map==='unavailable');assert.match($('mt-map').textContent,/selectores y la tabla/);
  assert.ok($('mt-streets').disabled);dom.window.close();
});
