import { createClient } from "npm:@supabase/supabase-js@2";
import { createRemoteJWKSet, jwtVerify } from "npm:jose@6";
const ISSUER="https://token.actions.githubusercontent.com",AUDIENCE="cepoes-supabase-press-drafts",REPOSITORY="cepoes100b/CEPOES",REF="refs/heads/main",WORKFLOW_REF=`${REPOSITORY}/.github/workflows/prensa-borradores.yml@refs/heads/main`;
const JWKS=createRemoteJWKSet(new URL(`${ISSUER}/.well-known/jwks`));
const respond=(status:number,body:unknown)=>new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json","cache-control":"no-store"}});
const text=(v:unknown,n=30000)=>String(v??"").replace(/\u0000/g,"").trim().slice(0,n);
async function authorize(req:Request){const m=(req.headers.get("authorization")||"").match(/^Bearer\s+(.+)$/i);if(!m)throw Error("bearer");const {payload}=await jwtVerify(m[1],JWKS,{issuer:ISSUER,audience:AUDIENCE});if(payload.repository!==REPOSITORY||payload.ref!==REF||payload.workflow_ref!==WORKFLOW_REF)throw Error("claims");}
function admin(){const url=Deno.env.get("SUPABASE_URL")||"";let key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";if(!key)try{const keys=JSON.parse(Deno.env.get("SUPABASE_SECRET_KEYS")||"{}");key=keys.default||Object.values(keys)[0]||""}catch{}if(!url||!key)throw Error("credentials");return createClient(url,key,{auth:{persistSession:false}})}
Deno.serve(async req=>{if(req.method!=="POST")return respond(405,{error:"method"});try{await authorize(req)}catch(e){console.error(e);return respond(401,{error:"unauthorized"})}let body:any;try{body=await req.json()}catch{return respond(400,{error:"json"})}const rows=(Array.isArray(body?.drafts)?body.drafts:[]).slice(0,20).map((x:any)=>({slug:text(x.slug,180),topic:text(x.topic,120),title:text(x.title,500),summary:text(x.summary,3000),facts:Array.isArray(x.facts)?x.facts:[],body:Array.isArray(x.body)?x.body.map((p:unknown)=>text(p)):[],quote:text(x.quote),methodology:text(x.methodology),source_label:text(x.source_label,1000),source_section:text(x.source_section,500),source_period:text(x.source_period,100),source_hash:text(x.source_hash,64),origin:"automatico",status:"borrador",created_by:null,updated_by:null})).filter((x:any)=>x.slug&&x.title&&/^[a-f0-9]{64}$/.test(x.source_hash));if(!rows.length)return respond(400,{error:"empty"});const db=admin();let inserted=0;for(const row of rows){const {data:exists,error:check}=await db.from("press_notes").select("id,status").eq("source_hash",row.source_hash).maybeSingle();if(check)return respond(500,{error:"check"});if(exists)continue;const {error}=await db.from("press_notes").insert(row);if(error){console.error(error);return respond(500,{error:"insert"})}inserted++}return respond(200,{received:rows.length,inserted})});
